apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: dr0l3/demo-orders
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "150m"
        ports:
        - containerPort: 80

