apiVersion: v1
kind: Service
metadata:
  name: user-preferences
spec:
  selector:
    app: user-preferences
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-preferences
spec:
  selector:
    matchLabels:
      app: user-preferences
  template:
    metadata:
      labels:
        app: user-preferences
    spec:
      containers:
      - name: user-preferences
        image: dr0l3/demo-preferences
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "150m"
        ports:
        - containerPort: 80

